---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-ci
  name: hello-ci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-ci
  template:
    metadata:
      labels:
        app: hello-ci
    spec:
      containers:
        - image: smazzone/helloci:latest
          name: hello-ci
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ci-service
spec:
  selector:
    app: hello-ci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

