---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-ci
  name: hello-ci
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-ci
  template:
    metadata:
      labels:
        app: hello-ci
    spec:
      containers:
        - image: {{.Values.image}}
          name: hello-ci
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false          
          ports:
          - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
