apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: hello-ci
 name: hello-ci
spec:
 replicas: 2
 selector:
   matchLabels:
     app: hello-ci
 template:
   metadata:
     labels:
       app: hello-ci
   spec:
     containers:
     - image: smazzone/helloci:1.0.0
       name: hello-ci
       ports:
       - containerPort: 3000
      #  resources:
      #    limits:
      #      memory: "512Mi"
      #      cpu: "500m"
      #    requests:
      #      memory: "256Mi"
      #      cpu: "250m"